services:
  - type: web
    name: sorbo-ingenierie-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server-mongodb.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://kevinyameogo01:wBLR2n5hAPNZM93Y@sorbo-ingenierie.ol32tmy.mongodb.net/?retryWrites=true&w=majority&appName=Sorbo-ingenierie
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: c670766d50129c7b7e59455fc7608991666bdeb5f5984ef6915b8a358a90c9c4
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: FRONTEND_URL
        value: https://sorbo-ingenierie.onrender.com
      - key: API_URL
        value: https://sorbo-ingenierie-backend.onrender.com/api 